### ISSUE TITLE
Strange data process in dataset_reader.py

### ISSUE THREAD

**Issue by JerrryNie** [allenai/qasper-led-baseline#15]
Hi, as the code shown in https://github.com/allenai/qasper-led-baseline/blob/afd0fb96bf78ce8cd8157639c6f6a6995e4f9089/qasper_baselines/dataset_reader.py#L205-L207 ,  is it a necessity only to choose the first element in the answer candidates and the corresponding evidence set when self._for_training is False ? I think it will lead to wrong (probably lower) evaluating results in Answer-F1 and Evidence-F1.
Instead, I think the mentioned three lines should be modified as:
```
            answers_to_yield = [x['text'] for x in all_answers]]
            evidence_masks_to_yield = all_evidence_masks
            evidence_to_yield = all_evidence
```

**Comment by pdasigi** [comment]
Hi @JerrryNie, note that the Answer F1 and Evidence F1 are computed against the strings and the evidence indices in the `metadata` field, which always contains information corresponding to all the reference answers/evidence. 
https://github.com/allenai/qasper-led-baseline/blob/afd0fb96bf78ce8cd8157639c6f6a6995e4f9089/qasper_baselines/model.py#L103-L112

https://github.com/allenai/qasper-led-baseline/blob/afd0fb96bf78ce8cd8157639c6f6a6995e4f9089/qasper_baselines/model.py#L136-L141

The code you referred to only affects the number of instances yielded per QA pair. We want multiple instances per QA pair (or one per reference answer/evidence) during training, and only one instance per QA pair during evaluation. During evaluation, the loss is computed against that reference, but the Answer F1 and Evidence F1 are computed against all references in the `metadata` field.

**Comment by JerrryNie** [comment]
Thanks! :)
