### ISSUE TITLE
(Probably) Redundant F1 computation

### ISSUE THREAD

**Issue by sheryc** [allenai/qasper-led-baseline#22]
Hi, I'm wondering if the F1 computation is redundant in the implementation. The `QasperReader` class yields an instance for every single *answer* instead of every single *question*, but the F1 score computation in `QasperBaseline` computes an F1 score for each input instance. This means that questions with more reference answers will generate more input instances, hence contributing more to the F1 score. Is it a bug or a standard approach? Thank you for your help!

**Comment by pdasigi** [comment]
Hi @sheryc, the reader yields one instance per reference only during training, and one instance per question during validation: https://github.com/allenai/qasper-led-baseline/blob/main/qasper_baselines/dataset_reader.py#L205-L208
But in both cases the metadata contains all the references: https://github.com/allenai/qasper-led-baseline/blob/main/qasper_baselines/dataset_reader.py#L201

The model computes F1 only during validation using the references in the metadata: https://github.com/allenai/qasper-led-baseline/blob/main/qasper_baselines/model.py#L103.

So this setup has the following effect:
1) during training, each instance corresponds to one reference, and loss is computed on every reference
2) during validation, each instance corresponds to one question (with potentially multiple references), and F1 is computed on all the references once; loss is computed only on the first reference during validation, but it does not matter much.

I realize this setup is indeed complicated. Hopefully the explanation is clear.

**Comment by sheryc** [comment]
Hi @pdasigi , thank you for your help! I realized that I missed the answer selection in https://github.com/allenai/qasper-led-baseline/blob/afd0fb96bf78ce8cd8157639c6f6a6995e4f9089/qasper_baselines/dataset_reader.py#L205. I'll close this issue.
