### ISSUE TITLE
Bug in calculating the paragraph indices list

### ISSUE THREAD

**Issue by soni-n** [allenai/qasper-led-baseline#25]
https://github.com/allenai/qasper-led-baseline/blob/main/qasper_baselines/dataset_reader.py#L293

https://github.com/allenai/qasper-led-baseline/blob/main/qasper_baselines/dataset_reader.py#L298C9-L298C31 

The code does not accommodate the paragraph_separator token when calculating the start of context, that makes the paragraph_separators as the  as the paragraph indices for each para. (paragraph_start_indices were correctly assigned as the first token of each para but the list misses the separator in the calculations.)

**Comment by pdasigi** [comment]
Hi @soni-n , the `paragraph_indices_list` is supposed to contain the indices of the separator tokens before each paragraph. I realize that the variable name is misleading. Thanks for pointing that out.

**Comment by soni-n** [comment]
Thanks for your response.
Is the intention to use the paragraph separator as the paragraph representation, similar to how the [CLS] token is used?

**Comment by pdasigi** [comment]
Yes, that's correct.
