### ISSUE TITLE
PyTorch compatibility issue?

### ISSUE THREAD

**Issue by soni-n** [allenai/qasper-led-baseline#26]
Hi,

I was able to run the scripts initially but off late I'm getting a CUDA error.

RuntimeError: CUDA error: no kernel image is available for execution on the device

PyTorch version: 1.12.1
Cuda 11.8
GPU RTX A6000
Python 3.8 (and 3.9)
Transformers 4.20 or 4.31 or 4.4 (defaulted from requirements.txt)

And with Transformers 4.33 it just throws the error: Segmentation fault (core dumped)

Can you please help me with which PyTorch version is used for this project and if you have any pointers that can fix this? Thanks!

**Comment by pdasigi** [comment]
@soni-n 
Looking at my old Conda environment, I see

```
torch==1.8.2+cu111
transformers==4.4.2
allennlp==2.2.0
```

Hope this helps.
